name: gateway
services:
  app:
    build: ..
    environment:
      - BACKEND_ENV=prod
      - NODE_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - nc
        - -vz
        - -w1
        - localhost
        - '8080'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
